ElectionsPrerequisites/Models/APIRequest.cs
using Microsoft.AspNetCore.Mvc;
using static ElectionsPrerequisites_Utility.SD;

namespace ElectionsPrerequisites.Models
{
    public class APIRequest
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
    }
}

ElectionsPrerequisites/Models/APIResponse.cs
using System.Net;

namespace ElectionsPrerequisites.Models
{
    public class APIResponse
    {
        public APIResponse()
        {
            ErrorMessages = new List<string>();
        }
        public HttpStatusCode StatusCode { get; set; }
        public bool IsSuccess { get; set; } = true;
        public List<string> ErrorMessages { get; set; }
        public object Result { get; set; }
    }
}

ElectionsPrerequisites/Models/Dto/ElectionCreateDTO.cs
using System.ComponentModel.DataAnnotations;

namespace ElectionsPrerequisites.Models.Dto
{
    public class ElectionCreateDTO
    {
        [Required]
        public string ElectionName { get; set; }
    }
}

ElectionsPrerequisites/Models/Dto/ElectionDTO.cs
using System.ComponentModel.DataAnnotations;

namespace ElectionsPrerequisites.Models.Dto
{
    public class ElectionDTO
    {
        public int Id { get; set; }
        [Required]
        public string ElectionName { get; set; }
    }
}

ElectionsPrerequisites/Models/Dto/ElectionUpdateDTO.cs
using System.ComponentModel.DataAnnotations;

namespace ElectionsPrerequisites.Models.Dto
{
    public class ElectionUpdateDTO
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string ElectionName { get; set; }
    }
}

ElectionsPrerequisites/Models/ErrorViewModel.cs
namespace ElectionsPrerequisites.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElectionsPrerequisites/Controllers/ElectionController.cs
using AutoMapper;
using ElectionsPrerequisites.Models;
using ElectionsPrerequisites.Models.Dto;
using ElectionsPrerequisites.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection;

namespace ElectionsPrerequisites.Controllers
{
    public class ElectionController : Controller
    {
        public readonly IElectionService _electionService;
        private readonly IMapper _mapper;
        public ElectionController(IElectionService electionService, IMapper mapper)
        {
            _electionService = electionService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexElection()
        {
            List<ElectionDTO> list = new();

            var response = await _electionService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ElectionDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        public async Task<IActionResult> CreateElection()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateElection(ElectionCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _electionService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexElection));
                }
            }
            return View(model);

        }
        public async Task<IActionResult> UpdateElection(int electionID)
        {
            var response = await _electionService.GetAsync<APIResponse>(electionID);
            if (response != null && response.IsSuccess)
            {
                ElectionDTO model = JsonConvert.DeserializeObject<ElectionDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<ElectionUpdateDTO>(model));
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateElection(ElectionUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _electionService.UpdateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexElection));
                }
            }
            return View(model);

        }
        public async Task<IActionResult> DeleteElection(int electionID)
        {
            var response = await _electionService.GetAsync<APIResponse>(electionID);
            if (response != null && response.IsSuccess)
            {
                ElectionDTO model = JsonConvert.DeserializeObject<ElectionDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteElection(ElectionDTO model)
        {
           
            
                var response = await _electionService.DeleteAsync<APIResponse>(model.Id);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexElection));
                }
            
            return View(model);

        }
    }
}

ElectionsPrerequisites/Controllers/HomeController.cs
using ElectionsPrerequisites.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ElectionsPrerequisites.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ElectionsPrerequisites/Views/Election/CreateElection.cshtml
@model ElectionsPrerequisites.Models.Dto.ElectionCreateDTO

<form asp-action="CreateElection">
    <br/>
    <div class="container border p-3">
        <h1 class="text-primary">Create Election</h1>
        <hr/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="ElectionName" class="control-label pt-2" style="font-size:20px;">
                </label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ElectionName" class=" form-control"/>
                <span asp-validation-for="ElectionName" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexElection" asp-controller="Election" class="btn btn-primary  form-control">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Create" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

ElectionsPrerequisites/Views/Election/DeleteElection.cshtml
@model ElectionsPrerequisites.Models.Dto.ElectionDTO

<form asp-action="DeleteElection">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Election</h1>
        <hr />

        <input hidden asp-for="Id" />
        <div class="row">
            <div class="col-2">
                <label asp-for="ElectionName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ElectionName" disabled class="form-control" />
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexElection" asp-controller="Election" class="btn-primary btn form-control ">Back to List</a>
            </div>
 
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElectionsPrerequisites/Views/Election/IndexElection.cshtml
@model IEnumerable<ElectionsPrerequisites.Models.Dto.ElectionDTO>
<br/>
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Election List</h1>
        </div>
        <div class="col text-end pt-1">
            <a class="btn btn-outline-primary" asp-controller="Election" asp-action="CreateElection"><i class="bi bi-plus-square-fill"></i> Create new Election</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Name
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model){
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ElectionName</td>
                    <td>
                        <a asp-controller="Election" asp-action="UpdateElection" asp-route-electionID="@item.Id" class="btn btn-outline-primary btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Election" asp-action="DeleteElection" asp-route-electionID="@item.Id"  class="btn btn-outline-primary btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ElectionsPrerequisites/Views/Election/UpdateElection.cshtml
@model ElectionsPrerequisites.Models.Dto.ElectionUpdateDTO

<form asp-action="UpdateElection">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Election</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Id" class="control-label pt-2" style="font-size:20px;">
                </label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Id" class=" form-control" readonly/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="ElectionName" class="control-label pt-2" style="font-size:20px;">
                </label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ElectionName" class=" form-control" />
                <span asp-validation-for="ElectionName" class="text-danger"></span>
            </div>
            
            <div class="col-5 offset-2">
                <a asp-action="IndexElection" asp-controller="Election" class="btn btn-primary  form-control">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

ElectionsPrerequisites/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ElectionsPrerequisites/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectionsPrerequisites</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElectionsPrerequisites.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ElectionsPrerequisites</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Election" asp-action="IndexElection">Election</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ElectionsPrerequisites - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>